### ISSUE TITLE
how to get the local variables and EH info ?

### ISSUE THREAD

**Issue by dmhai** [GeorgePlotnikov/ClrAnalyzer#7]
thx for share , but we need more info to dump the methods ,

now we have the ILCode, but how to get the local variables and EH info ?

**Comment by 0xGeorgii** [comment]
hi @dmhai. if you init new object then [newobj](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.newobj?view=netcore-3.1) il-command occurs. If you init local variable like int then [ldc.*](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.ldc_i4?view=netcore-3.1) occurs. Keep in mind local variables could be compiled aheah like:

```
.entrypoint
.maxstack  2
.locals init (int32 V_0, int32 V_1)
```

**Comment by 0xGeorgii** [comment]
Closed, with the given answer.
